### ISSUE TITLE
CIP-0002: Longest asset length is 14 characters

### ISSUE THREAD

**Issue by Jpja** [CounterpartyXCP/cips#1]
Not 12 as mentioned.

E.g. http://www.blockscan.com/assetInfo/BBSPONSORTOKEN

This is the longest name from current assets. What's the theoretical maximum?

**Comment by deweller** [comment]
The [counterparty docs](http://counterparty.io/docs/protocol_specification) say that the maximum is 12 so I checked this out.

As of block 340000, the maximum asset length is 12 ASCII Characters.

Here is the relevant commit 
https://github.com/CounterpartyXCP/counterparty-lib/commit/58de85567de3b4a0be8ea5c3406f476c95656754 (See line 471).

Before block 340000 all asset names that decoded into 8 bytes were allowed.  So it was possible to issue some asset names which could be 13 or 14 characters in length.
