### ISSUE TITLE
Reset as a parameter or keyword?

### ISSUE THREAD

**Issue by Jpja** [CounterpartyXCP/cips#55]
If I understand the Dogeparty implementation correctly, RESET is a new parameter added to the issuance message:

![image](https://user-images.githubusercontent.com/8447505/186594973-d63f1ec3-e0bb-424a-ad26-ceb7bd72ad90.png)

This comes with some negatives;
- not backwards compatible (e.g. javascript libraries need update)
- adds one bye, i.e. one less character for asset description to fit op_reuturn (from 45 to 44)

I suggest either do one of the following.

1. Remove `callable_`, `call_date`, `call_price`. These are deadweight and removing them will shave off 10 bytes. Net 9 bytes if RESET is added, meaning max description to fit opreturn increases to 54. Since the issuance message is altered anyway, this is the perfect time to remove the callability fields.

OR

2. Instead of adding a new parameter, set the RESET keyword as asset description. This would be consistent with how LOCK works. Existing wallets don't need to update.

**Comment by jdogresorg** [comment]
>"Instead of adding a new parameter, set the RESET keyword as asset description. This would be consistent with how LOCK works. Existing wallets don't need to update."

FYI... the asset description is not set to "LOCK" in the actual issuances table (the description remains the original description), using "LOCK" in the description is just a way to indicate that the user wants to lock the asset. the `lock` field is set to 1 when an issuance is a lock, the same thing happens with the `reset` field where it is set to 1 on a reset.

issuances now have a new `lock` and `reset` params which are set to 1 or 0 based on if this is a lock or reset

You can still use the old "LOCK" description method to lock the asset as well, but it basically just forces `lock=1` as if you used that param in the API request.

I agree with you on removing the callable fields, as they are just taking up space and have been disabled for a really long time.

**Comment by jdogresorg** [comment]
`callable`, `call_date`, and `call_price` have been removed from the issuance data in [PR #1209](https://github.com/CounterpartyXCP/counterparty-lib/pull/1209) and it is in testing

**Comment by jdogresorg** [comment]
closing this now as CIP03 is Active
