### ISSUE TITLE
Same tx_index in 'issuances' and 'destructions' tables?

### ISSUE THREAD

**Issue by Jpja** [CounterpartyXCP/cips#56]
From the chat I understand that a RESET will trigger a destruction if there's a non-zero balance. Does this means that a reset will cause updates to both the 'destructions' and 'issuances' tables?

If this is the case; just want to confirm that it's consistent with Counterparty logic that two tables can share the same 'tx_index' value. (?)

**Comment by jdogresorg** [comment]
Thanks for bringing this point up as I was not sure myself. 👍 

After some investigation, it seems that we already are using the same tx_index in multiple tables when we added the `sweep` functionality a couple years back. A single sweep transaction can create records in the `sweeps`, `issuances`, and `sends` table, all with the same `tx_index`.

I think we are fine continuing to use the same `tx_index` in the `issuances` and `destructions` tables.
