### ISSUE TITLE
Subasset requirements

### ISSUE THREAD

**Issue by Jpja** [CounterpartyXCP/cips#6]
Awesome CIP!
Just think it would be good to discuss the requirements before mainnet launch.

My two cents:
* The name should be short of enough for wallet display. Maybe 40 characters max?
* Will allowing both lowercase and uppercase add any value? Why not limit characters to 'A-Z0-9.-' ?
* Unlike for ordinary asset, a XCP fee is not needed to discourage squatting. For subassets, a fee is only needed to prevent database bloating. Wouldn't something like 0.1 XCP be sufficient?

**Comment by deweller** [comment]
Closing in favor of moving the discussion to https://counterpartytalk.org/t/subassets-a-proposal/1690/27
