### ISSUE TITLE
I’m not a fan of sub assets. Think they are a toxic idea.

### ISSUE THREAD

**Issue by jsmith-dev** [CounterpartyXCP/cips#9]
So I have spent the past 24 hours looking at sub-asset CIP.

Technically there is a case for both x.x.asset or asset.x.x ordering as proposed.

But either ordering option isn't the key flaw, nor is the technical embodiment.

Why this idea is so dead on arrival, in my opinion, is that it is fundamentally at odds with and damaging to assets as fiduciary instruments.

This is a 'death by adding features' track rather than a 'refinement by taking away as much as possible until it stops making sense to take away any more' approach.

Today - Assets are designated specific namespace:

They have utility as this and on this basis.

*PLEASE* don't dilute the very nature of the CP project by introducing domain name style system.

It is a toxic idea and I actually strongly oppose.

It may make sense to allow the "." character in asset names... but the omnibus name hierarchy system proposed in CIP-0004 seems damaging and undesirable.

I move to raise an objection on CIP-0004 and for it to be categorised as contentious.

[All opinions are my own (Julian Smith) and do not reflect the stated position of any organisations or companies in which I am an investor or representative]

**Comment by jsmith-dev** [comment]
In further discussion around this - a proposed embodiment is:

Using the colon ":" as asset / sub-asset separator.

With double colon "::" being the separator adjacent to the root asset.

Pull-requests coming, soon™

**Comment by deweller** [comment]
@jsmith-dev Can you please join the discussion at https://counterpartytalk.org/t/subassets-a-proposal/1690/27.  That is the official discussion record.
